### ISSUE TITLE
Any reason not to support Python 3.10 and 3.11?

### ISSUE THREAD

**Issue by dimaqq** [kimetrica/django-binary-database-files#49]
Current state: https://github.com/kimetrica/django-binary-database-files/blob/0e618741d76c04bff2a47bf80462643da1cd4df5/setup.py#L62

**Comment by rhunwicks** [comment]
https://pypi.org/project/django-binary-database-files/1.0.16/ is released and supports Python 3.10.  We will open another ticket to track Python 3.11 support, after that Python version is released.
